name: Build firmware

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: docker://qmkfm/base_container:latest
      volumes: 
        - .:/qmk_firmware

    steps:
    - uses: actions/checkout@v2
    - uses: docker://qmkfm/base_container:latest
    - name: make
      run: |
        wget -P /tmp https://github.com/abcminiuser/lufa/archive/master.zip
        unzip -d /tmp /tmp/master.zip > /dev/null
        mv /tmp/lufa-master/LUFA lib/lufa/
        make keebio/iris/rev2:lorentzca
        mv -v .build/keebio_iris_rev2_lorentzca.hex .build/keebio_iris_rev2_lorentzca_${GITHUB_RUN_ID}.hex
    - uses: actions/upload-artifact@v1
      with:
        name: firmware
        path: .build/keebio_iris_rev2_lorentzca_${{ github.run_id }}.hex
